version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: modelsecurity_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: modelsecurity
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - modelsecurity_network

  postgres:
    image: postgres:16
    container_name: modelsecurity_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: modelsecurity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - modelsecurity_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: modelsecurity_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "123456"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - modelsecurity_network

volumes:
  mysql_data:
  postgres_data:
  sqlserver_data:

networks:
  modelsecurity_network: