spring:
  application:
    name: modelsecurity
  profiles:
    active: postgresql

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  jwt:
    secret: mySecretKey
    expiration: 86400000
    expiration-ms: 86400000

server:
  port: 8081

---
# PERFIL: MySQL (Local)
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/modelsecurity
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration/mysql

---
# PERFIL: MySQL (Docker)
spring:
  config:
    activate:
      on-profile: mysql-docker
  datasource:
    url: jdbc:mysql://mysql:3306/modelsecurity
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration/mysql

---
# PERFIL: PostgreSQL (Local)
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/modelsecurity
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration/postgresql

---
# PERFIL: PostgreSQL (Docker)
spring:
  config:
    activate:
      on-profile: postgresql-docker
  datasource:
    url: jdbc:postgresql://postgres:5432/modelsecurity
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration/postgresql

---
# PERFIL: SQL Server (Local)
spring:
  config:
    activate:
      on-profile: sqlserver
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=modelsecurity;encrypt=false
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
  flyway:
    locations: classpath:db/migration/sqlserver

---
# PERFIL: SQL Server (Docker)
spring:
  config:
    activate:
      on-profile: sqlserver-docker
  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=modelsecurity;encrypt=false
    username: sa
    password: "123456"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
  flyway:
    locations: classpath:db/migration/sqlserver